# Generated by Django 5.1.2 on 2024-11-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_domain',
            field=models.CharField(default='empty', max_length=255),
            preserve_default=False,
        ),
    ]
