# Generated by Django 5.1.2 on 2024-11-14 17:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser_user_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sidenote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000, validators=[django.core.validators.URLValidator()])),
                ('text', models.TextField()),
                ('domain', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customuser')),
            ],
            options={
                'indexes': [models.Index(fields=['domain'], name='main_sideno_domain_b05c73_idx'), models.Index(fields=['author'], name='main_sideno_author__001875_idx')],
            },
        ),
    ]
