# Generated by Django 5.1.2 on 2024-11-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sidenote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_hash',
            field=models.CharField(default='pomidor', max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='token',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
